name: Run Pytest Workflow

on: push

jobs:
  GitHub-Tests:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'    

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |     
        python -m pip install --upgrade pip
        pip install -r requirements.txt
  
    - name: Run tests   
      env: 
        PL_API_KEY: ${{ secrets.PL_API_KEY }}
        PYTHONPATH : ${{ github.workspace }}  
      run: |
        pytest tests/data/*
